<!DOCTYPE html>
<html lang="fr">
    <head>
        <title>Le spécialiste de l'info sur ONE PIECE</title>
        <meta charset="utf-8"/>     
        <link rel="stylesheet" href="/css/visu.css"/>
    </head>
    <body>
        <header>
            <!--Menu qui s'ouvre afin de pouvoir sélectionner l'un des différent equipage que l'on souhaite voir-->
            <?php include('../menu.php');?>
        </header>
        <main>
            <section class="descP">
                <h1>Monkey D. Luffy</h1>
                <figure>
                    <img src="/image/Luffy/luffy_p/Monkey_D._Luffy_Anime_Post_Ellipse_Infobox.png" alt="Luffy" class="mainImg">
                </figure>
                <p>Monkey D. Luffy (モンキー・Ｄディー・ルフィ, Monkī Dī Rufi) est un pirate et le principal protagoniste du manga et anime One Piece. Luffy est le fils du chef de l'Armée Révolutionnaire, Monkey D. Dragon, le petit-fils du célèbre Vice-Amiral de la Marine, Monkey D. Garp, le fils adoptif d'une bandit des montagnes, Curly Dadan ainsi que le frère adoptif du défunt Portgas D. Ace et de Sabo. Son rêve le plus cher est de devenir le Seigneur des Pirates en trouvant le trésor légendaire One Piece, caché quelque part dans le monde par Gol D. Roger. Selon lui, être le Seigneur des Pirates signifie être celui qui jouit d'une liberté sans pareille dans le monde. Il a mangé un Fruit du Démon : le Gomu Gomu no Mi, qui a été rapporté lors d'un voyage par L'Équipage du Roux au Village de Fuchsia, à ce moment là</p>
                <p>En tant que fondateur et Capitaine de l'Équipage du Chapeau de Paille, il est le premier membre à en faire partie, ainsi que l'un des trois combattants les plus forts de ce dernier, s'il n'est le plus fort. C'est également le fondateur involontaire de La Grande Flotte du Chapeau de Paille, il refuse cependant d'en être le Capitaine, ne désirant pas priver les autres de leur liberté.</p>
                <p>Luffy a une réputation mondiale pour avoir causé des troubles et des catastrophes, même parmi les 7 Capitaines Corsaires et la Marine, en étant allé jusqu'à défier deux des Quatre Empereurs (Big Mom et Kaidô), ainsi qu'en commettant des crimes et actions considérées comme dangereuses par le Gouvernement Mondial. Il a reçu la réputation d'être "téméraire" et "fou", dans certains cas. Il est, en effet, célèbre pour avoir fait brûler le drapeau du Gouvernement Mondial à Enies Lobby (il s'agissait d'un ordre donné à Sogeking), avant d'y vaincre le CP9 avec son équipage; avoir frappé un Dragon Céleste à Sabaody; vaincu plusieurs des 7 Grands Corsaires (Crocodile, Gecko Moria ou Doflamingo); s'être infiltré et échappé d'Impel Down en y causant une gigantesque évasion (la plus grande de l'histoire de la prison); et s'être joint à la Bataille de Marine Ford, du côté de l'Équipage de Barbe Blanche. De plus, il est connu pour être le seul pirate à s'être non seulement infiltré dans les trois installations capitales du Gouvernement, mais aussi pour s'être échappé vivant de toutes les trois. Ce passé de fauteur de troubles valut rapidement à Luffy le qualificatif "d'élément dangereux dans le futur", notamment pour l'Amiral Commandant en Chef Sakazuki, faisant de la Marine l'un de ses plus grands ennemis.</p>
                <p>Ses actes, entre autres, se sont traduits par une prime actuelle de 1 500 000 000. Ayant eu une prime de 300 000 000 avant son arrivée à l'Archipel Sabaody, Luffy était l'un des onze pirates de renom dont on fait référence en tant que "Onze Supernovae", les onze pirates avec des primes dépassant les 100 000 000 et qui sont arrivés en même temps sur l'Archipel Sabaody.</p>
            </section>
            <aside id="Summ">
                    <h1> Sommaire</h1> 
            <ol>    
                <li><a href="#App"> Apparence</a> 
                    <ol>
                        <li><a href="#AG"> Apparence Générale</a></li>
                        <li><a href="#APoE"> Apparence Pré Elipse</a></li>
                        <li><a href="#APrE"> Apparence Post Elipse</a></li>
                    </ol>
                </li>
                <li><a href="#Pers"> Personnalité</a> </li>
                <li><a href="#Gal"> Galerie</a> </li>
            </ol>
            </aside>
            <section class="descP">
                <h1 id="App">Apparence</h1>
                    <h2 id="AG"> <a href="#Summary">Apparence Générale</a></h2>
                    <p> Luffy est réputé pour porter son Chapeau de Paille (d'où son épithète "Luffy au Chapeau de Paille") que le légendaire capitaine pirate Shanks "le Roux" lui a confié lorsqu'il était jeune, ce dernier le tenant lui-même de Roger. Luffy a également une cicatrice avec deux points de suture sous son œil gauche (blessure qu'il s'est lui-même infligée avec un couteau sous l’œil pour prouver son courage à Shanks), et des cheveux noirs assez courts.</p>
                    <p>Similaire à la plupart des hommes de son équipage, Luffy porte la plupart du temps les mêmes vêtements, à l'opposé du reste de l'équipage (spécialement <a href="#">Nami</a> et <a href="#">Nico Robin</a>), qui quant à elles, changent fréquemment de tenues.</p>
                    <p>Quel que soit l'endroit où il se trouve, Luffy porte en toutes circonstances son Chapeau de Paille, même si au début, le chapeau pouvait facilement tomber de sa tête, car instable, ce qui forçait Luffy à le mettre de côté, ou à demander à quelqu'un de le tenir pour lui (le plus souvent à Nami).</p>
                    <h2 id="APoE"> <a href="#Summary">Apparence Pré Elipse</a></h2>
                    <p>Il porte des pantalons courts ainsi que des sandales et une veste rouge sans manches. Ayant l'air un peu maigre sous sa chemise, il a pourtant un physique étonnamment bien bâti. Il est assez petit, éclipsé par beaucoup de personnages de la série plus grands.</p>
                    <p>Luffy peut porter une tenue différente pour s'adapter au climat des différentes îles (comme un parka à capuchon pour l'Île de Drum ou une robe du désert pour Alabasta), mais se revêtit de sa veste et de ses bermudas dès que ses aventures sur les îles sont terminées. En dépit de cela, il portera sa tenue habituelle dans différentes couleurs et a été connu pour porter divers autres articles sur lui de temps en temps.</p>
                    <p>Durant l'Arc Île de Drum, il porta deux parkas, le premier étant un parka rouge foncé avec de la fourrure sur les manches, le capuchon et les ourlets, puis un parka encapuchonné à carreaux avec les couleurs suivantes : blanc, orange et jaune pâle que Nami portait au début.</p>
                    <p>Durant l'Arc Alabasta, il porta une robe du désert constituée d'une robe rouge foncée munie de trois anneaux blancs décorés sur les deux manches et d'un châle bleu pâle au-dessus de sa tête. Il reçoit également un cordon pour son Chapeau de Paille, qui a été cousu par Nami, ce qui permet au chapeau de rester accroché à son cou durant les combats.</p>
                    <p>Durant l'Arc Skypiea, il porta un bracelet noir autour de son poignet gauche, surmonté d'un anneau blanc.</p>
                    <p>Durant l'Arc Davy Back Fight, Luffy porta une coupe afro, un short rouge foncé et des bandages rouges aux pieds, ainsi que des tatouages formant un crâne enflammé et des tibias bleus peints sur sa poitrine quand il se battait contre Foxy "le Renard Argenté".</p>
                    <p>Durant l'Arc d'Enies Lobby, il porta un short noir pourvu de poches dans lesquelles il pouvait transporter de la viande.</p>
                    <p>Durant l'Arc Post-Enies Lobby, Luffy porta un T-shirt blanc avec l'emblème inscrit en rouge de la Galley-La Company, ainsi que des doublures rouges autour du haut des épaules et du collier, accompagné d'un short bleu marine.</p>
                    <p>Durant l'Arc de Thriller Bark, il porta une veste orange et un short rouge. Après son combat contre Moria à Thriller Bark, Luffy portait un brassard sombre assez décoré autour de son biceps gauche. Ce brassard se révéla plus tard être une carte qui conduit au trésor perdu du Capitaine John, dont Baggy avait entrepris la recherche depuis peu, ce qui a amené Luffy à lui remettre le brassard en échange de ses services pour l'aider à s'orienter à l'intérieur de la prison d'Impel Down.</p>
                    <p>Durant l'Arc de Sabaody, il porta une veste bleue foncée et un short bleu marine.</p>
                    <p>Durant l'Arc Amazon Lily, notre Chapeau de Paille porta une veste bleue pâle assortie d'un short rouge.</p>
                    <p>Durant l'Arc Impel Down, Luffy porta la tenue de son aventure à Amazon Lily, juste après son combat avec Magellan, où il remplaça sa veste bleue par une veste jaune pâle que Inazuma lui fournît.</p>
                    <p>Durant l'Arc Marine Ford, malgré que Jinbe l'ait protégé avec son corps, Luffy fut sévèrement blessé par une attaque d'Akainu, lui laissant sur son torse, sa fameuse cicatrice en forme de X.</p>
                    <p>Durant son retour à Marine Ford, pour effectuer une prière silencieuse, Luffy a été vu brièvement avec quatre caractères écrits sur son bras droit : "3D2Y", le "3D" étant barré pour faire comprendre à son équipage qu'ils devront se réunir d'ici 2 ans ("2Y" pour "2 years") au lieu des 3 jours ("3D" pour "3 days") convenus, suite à leur défaite face à Bartholomew Kuma et à la décision de Luffy de s'entraîner pour pouvoir survivre jusqu'à la fin du voyage.</p>
                    <h2 id="APrE"> <a href="#Summary">Apparence Post Elipse</a></h2>
                    <p>Après ces deux ans, Luffy est vu avec un gilet de laine rouge avec 4 boutons au-dessus (ce qui montre la cicatrice en forme de X couvrant la majeure partie de sa poitrine, preuve de l'attaque quasi-mortelle qui lui fut infligée par l'ex-Amiral Akainu), et un foulard jaune autour de sa taille, rappelant un peu la tenue de Roger. Il n'a pas grandi de façon significative (2 cm de plus), mais il s'est avéré être devenu plus musclé en raison de son entraînement herculéen et est beaucoup plus fort. Le fruit de cet entraînement peut être vu dans la mesure où son cou est légèrement plus épais avec des deltoïdes plus prononcés et une poitrine également plus large. En outre, il essaie de paraître discret à l'aide d'une fausse barbe blanche et des lunettes de soleil, pour ne pas se faire repérer par la Marine (ce qui n'a finalement pas abouti du fait des capacités des Pacifistas). Ce costume amène le plus souvent à des situations comiques.</p>
                    <p>Durant l'Arc Dressrosa, Luffy porte une chemise bleue foncée avec des motifs oranges-jaunes évoquant des fleurs ou des soleils. Lors du tournoi au Colisée Corrida, il ressort le déguisement barbe-lunettes (et se renomme dans la foulée "Lucy"). Il va également porter très brièvement un déguisement de poisson rouge avec un chignon, afin de s'introduire au Palais Royal.</p>
            </section>
            <section class="descP">
                <h1> <a href="#Summary" id="Pers">Personnalité</a></h1>
                    <p> Luffy se caractérise principalement par son manque apparent d'intelligence et son audace illimitée . Il l'a montré pendant la bataille contre Don Krieg en n'hésitant pas une seconde à frapper sa cape hérissée de pointes ou en continuant à courir vers lui malgré les pieux et les billes explosives qui le percutent de plein fouet. Il peut faire preuve d'une extrême détermination, comme lors de son combat contre Crocodile en le pourchassant à chaque fois pour à nouveau le combattre ou encore à Marineford où (malgré tous les coups qu'il encaissait) il continuait à avancer vers l'échafaud pour sauver son frère Ace de la Marine. Il peut être facilement ébahi par les choses les plus simples, comme des crabes ermites, et être confus face à des problèmes ou des situations qui requièrent de la logique. Il aime les monstres et les créatures atypiques et demandera à n'importe quel être bizarre de se joindre à son équipage (c'est le cas lors de l'Arc Thriller Bark où il demande à un arbre parlant qu'il trouvait drôle de les rejoindre). Il n'a aucune connaissance en médecine : lorsque Nami tomba malade, il proposa qu'on lui donne de la viande pour qu'elle guérisse ou qu'on lui jette de l'eau à la figure pour faire baisser sa température [24], plus tard, il essaya de soigner Zoro (après son combat contre Kuma) en versant du saké sur lui puisque ce dernier adore l'alcool [25]. Alors qu'il essayait de trouver un plan pour quitter Amazon Lily, au moment où il parvient (enfin !) à effectuer un raisonnement logique, il cède sous la pression et remarque qu'il va se sentir malade à trop penser.    </p>
                    <figure class="citation"> "La viande, y a que ça de vrai !"
                        <figcaption class="citAuthor"> Luffy et ses goûts culinaires</figcaption>
                    </figure>
                    <p>Son esprit simple l'a néanmoins sauvé du pouvoir de Hancock parce qu'il a confondu son Mero Mero no Mi avec un Noro Noro no Mi, utilisé par Foxy, ce qui l'a poussé à craindre d'être ralenti (quoiqu'il est révélé plus tard qu'il est immunisé de son pouvoir à cause de son cœur pur). Si Luffy trouve quelque chose qu'il ne comprend pas, même si quelqu'un lui explique en détail, il l’appellera une "chose mystérieuse", comme la Dance Powder qu'il appelle "poudre mystère". L'un des gags en série de Luffy est qu'il demande à des "non-humains" tels que Camie et Brook s'ils peuvent "faire popo", donc, dans chacun des cas, la réponse est habituellement un oui. Un autre gag en série est la réaction à retardement de Luffy au climat, en particulier à la neige et à la température de congélation, et aussi lorsqu'il se rendra compte un peu tard à Amazon Lily qu'il était entièrement nu.</p>
                    <figure>
                         <img src="/image/luffy/luffy_p/Luffy_oiseau.png" alt="Luffy qui se fait bouffer par un oiseau" class="imgLeg">
                         <figcaption class="descImg"> Luffy dans le bec d'un oiseau </figcaption>
                    </figure>
                    <p>Cependant, la même chose ne peut être dite lorsqu’il est sur le champ de bataille, il est connu pour esquiver avec facilité les attaques ennemies. On a déclaré plus d’une fois que le comportement et l’instinct de Luffy sont similaires à ceux d’un animal sauvage, comme quand il sait qu'il doit se battre avant même qu’il se joigne à la bataille. Même la façon dont il se bat le démontre, quand il s’appuie sur ses instincts et esquive des attaques. Il voit le monde de façon optimiste et il est le plus souvent vu en train de sourire, sauf lors des combats où il est obligé d’utiliser toutes ses capacités (et encore).</p>
                    <p>Le fait de voir le monde de façon très optimiste est très perturbant, car il peut s'aventurer dans un combat même avec un handicap certain comme lorsqu'il se bat contre Ener alors qu'il est contraint de porter une boule en or massif.</p>
                    <p>Côté personnalité, Luffy semble rarement changer. Puisqu'il voit le monde d'une manière simple et directe, il est parfois la seule personne qui peut comprendre les évènements passés et réaliser leur véritable but, mais à d'autres moments, il peut tomber dans le plus simple des pièges (comme un trou dans le sol).</p>
                    <figure>
                        <img src="/image/luffy/luffy_p/Golden_Luffy.PNG.png" alt="Golden Luffy" class="imgLeg">
                        <figcaption class="descImg"> Le Golden Luffy </figcaption>
                    </figure>
                    <p>Il est cependant un génie lorsqu'il s'agit du combat, tel que quand il a cassé la pointe de la "lance détonante" de Don Krieg pour qu'elle perde une partie de son efficacité. Quand il a découvert comment neutraliser les pouvoirs du Fruit du Démon de Crocodile au seuil de la mort, comment utiliser le Soru rien qu'en observant les membres du CP9, développer des contre-mesures efficaces face au pouvoir "Mantra" d'Ener et, plus récemment, apprenant tout ce que Rayleigh pouvait lui enseigner à propos du Fluide (Haki) en un an et demi (même si Rayleigh a mentionné que deux ans ont été un temps trop court pour tout lui apprendre sur le Fluide). Il a aussi l'habitude de tenir une rancune même dans des situations catastrophiques (comme en traitant Franky de "bâtard" au milieu de son combat contre Rob Lucci, entraînant Franky à répliquer "Ce n'est pas le moment d'avoir une dent contre moi" et en refusant à Crocodile de l'aider à s'échapper d'Impel Down même lorsqu'il n'y avait aucune autre alternative).</p>
                    <p>Cependant, il essaie de ne pas blesser des civils et des gens qu'il aime. Même s'ils ont l'intention de lui faire du mal, il préfère s'enfuir loin d'eux plutôt que de se battre.</p>
                    <p>Oda a dit que lorsqu'il le dessine, il tente de rendre Luffy très simple sur ce qu'il veut faire et comment il se sent. C'est pourquoi, de tous les personnages principaux, il a le moins de bulles de pensées, puisqu'il agit et dit ce qu'il veut faire plutôt que de le penser. Pour accentuer la naïveté et l'attitude simple de Luffy, il y a un gag récurrent à travers la série dans lequel Luffy est capable de trouver des similitudes entre des choses qui ont peu de ressemblance (comme être capable de voir la ressemblance entre Sanji et son avis de recherche, ou être capable de voir Spoil en tant que vieil homme avec des blessures majeures plutôt qu'un zombie), mais est incapable de voir les similitudes entre les choses avec des connections évidentes (ainsi il n'a jamais réalisé que Sniperking est Usopp et se fait berner par les déguisements pathétiques de Foxy).</p>
                    <p>Il possède de plus un penchant naturel pour l'imitation, comme on le voit imiter Zoro, Sanji, Chopper,... et ce même dans les pires situations comme lorsqu'il est prisonnier de Crocodile ou sur un chemin dangereux. Il est extrêmement naïf, comme Chopper, il croit à toutes les fables d'Usopp, comme celle citant un équipage de 8000 hommes, se laisse berner par tous les déguisements de Foxy... etc.</p>
                    <figure>
                        <img src="/image/luffy/luffy_p/Luffy_sanji.jpg" alt="Luffy qui imite Sanji" class="imgLeg" >
                        <figcaption class="descImg">Luffy qui imite Sanji</figcaption>
                    </figure>
                    <p>Les commentaires naïfs et les attitudes simples de Luffy durant les combats sont souvent interprétés à tort par ses adversaires comme étant des moqueries à leur égard. De ce fait, la plupart de ses adversaires perdent leur sang-froid et foncent vers lui en colère. Alors qu'il est maladroit et téméraire, il devient assez sérieux quand quelqu'un est en grand danger, notamment les membres de son équipage, qu'il considère comme ses amis. Il n'hésite pas une seconde à venir secourir Nami à Arlong Park alors qu'elle les avait trahie, ou à secourir Robin quitte à se mettre à dos le monde entier. Luffy a également tendance à se moquer, sans le vouloir, des caractéristiques les plus sensibles d'une personne, comme en appelant Baggy "Gros Pif", Alvida "grosse folle" et Kureha "Vieille Sorcière" ou encore en se moquant de la voix de Pica.</p>
                    <p>Dans de nombreux cas, les opposants n'arrivent pas à comprendre si Luffy est sérieux ou s'il ne fait que jouer durant les batailles à cause de ses actions bizarres comme boire beaucoup trop d'eau dans son combat avec Crocodile ou frapper les dents d'Arlong pour les briser et les utiliser en tant qu'armes pour le mordre. Cependant, Luffy a maintenu qu'il est toujours sérieux durant les combats. Dans la plupart des cas, dès qu'il commence une bataille, il maintient une attitude sérieuse et est vu en train de rire seulement lorsqu'il met K.O. un ennemi ou qu'il est certain que l'ennemi sera vaincu. Tel fut le cas pour Baggy quand il riait avant de l'envoyer dans les airs. </p>
                    <figure>
                        <img src="/image/luffy/luffy_p/Luffy_arlong.jpg" alt="L'idée géniale de Luffy" class="imgLeg" >
                        <figcaption class="descImg"> L'idée géniale de Luffy vs Arlong </figcaption>
                    </figure>
                    <p>Chaque fois que Luffy bat un adversaire ou un ennemi, si quelque chose de divertissant ou de comique se produit, Luffy sourit. Il n’y a eu qu’une seule exception : après son combat avec Usopp à Water 7, Luffy n’a pas souri pendant un jour entier, mais cela équivaut à 15 chapitres, c'est-à-dire la plus longue durée sans sourire de toute l'histoire.</p>
                    <p>Dans la bataille, Luffy a montré des signes d'intelligence et de hautes compétences tactiques et innovantes. Il peut facilement s'adapter à des situations assez difficiles telles que le Candle Lock de Mr. 3 et le Gloam Paddling d'Ener dans une attaque. Il utilise aussi un miroir pour refléter l'attaque Noro Noro Beam de Foxy. Durant l'Arc Marineford, Mihawk mentionne que Luffy semble anormalement réfléchi en évitant ses attaques. De plus, durant son combat contre Mihawk, il utilise Baggy comme un bouclier bouc-émissaire pour l'aider à se protéger et aller de l'avant vers Ace. Luffy a également l’habitude de dire des choses avec beaucoup plus de profondeur et (parfois) de sagesse sans même y penser ou le vouloir.</p>
                    <figure>
                        <img src="/image/luffy/luffy_p/Mizu_Luffy.png" alt="Aqua Luffy" class="imgLeg">
                        <figcaption class="descImg"> Luffy en Aqua Luffy vs Crocodile </figcaption>
                    </figure>
                    <p>La seule chose que Luffy ne peut se permettre, c’est quand quelqu’un ou quelque chose s’implique dans le combat d’une autre personne. Lors de ces moments, Luffy montre à la fois une retenue remarquable pendant les batailles, et une forte rage quand quelque chose ou quelqu’un en dehors de la bataille est impliqué, surtout si c’est une personne qu’il considère comme un ami. Luffy montre ceci tôt dans la série quand Roronoa Zoro combat Mihawk et réussit à se tenir en arrière (avec Johnny et Yosaku) jusqu’à ce que Zoro soit vaincu. Depuis, il l’a montré à plusieurs reprises, comme lorsque Baroque Works sabota le duel des deux géants à Little Garden ; quand Crocodile attaqua Yuba avec une tempête de sable en plein milieu de leurs combats ; quand il défia Aokiji à un combat singulier, quand il affronta Lucci et qu’il insista pour que Franky ne se mêle pas de leur combat ; quand les sœurs Boa menacèrent de briser les formes pétrifiées de ses sauveuses, et quand il était visiblement enragé contre Hody qui attaquait des civils qui essayaient de stopper Noah. Il alla même jusqu'à couvrir la marque dans le dos de Sandersonia des citoyennes de Kuja alors qu’il était encore brûlant, même si elles ont essayé de le tuer, clamant que ça n’avait rien à voir avec leurs combats.</p>
                    <p>Un autre gag récurrent est que, durant les combats, Luffy est toujours projeté dans des situations, soit par accident ou bien volontairement, dans lesquelles il ne peut pas combattre. Lorsqu'il est dans une situation comme celle-ci, les membres de son équipage affrontent généralement des personnes plus faibles associées à l'antagoniste principal et les mettent K.O., afin que personne d'autre n'interrompe le combat de Luffy. Ainsi, lorsque tous les autres ennemis sont vaincus, Luffy affronte le plus fort, c'est-à-dire le seul que uniquement Luffy peut vaincre. Ça arrive dans plusieurs arcs, tel que lorsqu'il est pris dans une cage dans l'Arc Baggy le Clown, endormi dans l'Arc Capitaine Kuro, pris dans un rocher et jeté à l'eau dans l'Arc Arlong, perdu, sérieusement blessé et en train de se reposer ou pris à l'intérieur de l'estomac d'un serpent géant dans l'Arc Skypiea.</p>
                    <p>Remarque :
                        C'est donc un schéma assez classique dans One Piece, qui peut être mis en parallèle avec la Bataille de Marine Ford où le commandant de la première flotte de l'équipage de Barbe Blanche, Marco indique à Kizaru qu'il est très difficile d'atteindre le roi directement sans passer par ses "sbires", ici son équipage. Ainsi, il en est de même pour l'équipage de Luffy. Pour exemple, lors de l'arc des hommes-poissons, Luffy voulant s'attaquer à Hody Jones, il se fait attaquer par ses sbires qui eux-mêmes se font à leur tour arrêter respectivement par Sanji et Zoro.</p>
                    <p>La personnalité de Luffy est comme celle d’un enfant, dans le sens où il a tendance à donner son maximum à chaque moment. Il peut être, soit extrêmement égoïste, surtout en ce qui concerne la nourriture, son équipage et l’aventure ; ou extraordinairement généreux, allant même jusqu'à presque se sacrifier lui-même pour venger ou protéger ses amis, son équipage et sa famille. Cette mentalité enfantine lui permet d'aller à la racine du problème et lui permet de comprendre la manière la plus simple pour le résoudre.</p>
                    <figure class="citation"> "J'ai aucune envie de savoir où se trouve ce trésor, ni même si ce trésor existe vraiment. Personne n'en sait rien et pourtant, on est tous là à risquer notre vie sur ces mers dangereuses. Si on doit demander des infos au papy pour retrouver ce trésor alors je préfère arrêter d'être un pirate ! J'ai envie d'adrénaline et d'aventure, pas de calme plat."
                        <figcaption class="citAuthor">Luffy à propos du One Piece et des connaissances de Rayleigh</figcaption>
                    </figure>
                    <p>Luffy a une soif extrême d'aventure, dont il dit que c'est la raison principale pour laquelle il veut devenir le Seigneur des Pirates, ayant la conviction que le Seigneur des Pirates serait l'homme le plus libre de tous les océans. Cette nature aventureuse a aussi tendance à lui faire éviter parfois la "route la plus facile", tel que lorsqu'il détruit l'Eternal Pose indiquant Alabasta donné par Robin (Miss All Sunday à l'époque), indiquant qu'il ne veut pas qu'un ennemi lui indique la destination à prendre. Il n'a également aucune intention de savoir où est ou ce qu'est le One Piece jusqu'à ce qu'il le trouve lui-même, ou même s'il existe vraiment. Luffy ne dit jamais adieu à ceux qu'il considère comme ses amis, dans l'espoir de les revoir à nouveau.</p>
                    <p>En tant que personne avec l'initiale D., Luffy partage la caractéristique commune de ne pas craindre la mort. Il dira souvent que s'il atteint son but, ça lui convient, mais s'il meurt en chemin, ça lui va aussi. Il sourit même lorsqu'il est sur le point d'être exécuté par Baggy à Loguetown, bien qu'il ait eu l'air choqué et surpris avant que ça n'arrive, lorsque Zoro et Sanji essaient de le sauver. Tout au long de la série, plusieurs personnages ont indiqué des similitudes entre Luffy et d’autres porteurs du D., que ce soit dans la personnalité, les paroles, les actions ou la présence. Jusqu’à présent, il est considéré comme semblable à Haguar D. Sauro par Robin ; à son grand-père Monkey D. Garp par Aokiji, l’un des membres du Conseil des 5 Étoiles et par son propre équipage ; à son père Monkey D. Dragon par Emporio Ivankov, à son frère Portgas D. Ace par Tama et à Gol D. Roger lui-même par Smoker, Crocus, Gan Forr, Shanks, Rayleigh, Kokoro et le personnage non-canonique, Raoul.</p>
                    <p>Comme plusieurs autres porteurs du D. vus jusqu'à présent, il est aussi un glouton (à l'image de Portgas D. Ace, Monkey D. Garp, Marshall D. Teach et peut-être Gol D. Roger et Haguar D. Sauro ; on ignore cependant ce qu'il en est dans le cas de Portgas D. Rouge et Monkey D. Dragon, personnes les plus sérieuses parmi les D.), malgré son apparence maigre : il aime la viande en particulier et peut manger un poisson en entier – y compris les os Un gag en série montre Luffy volant constamment la nourriture des autres avec ses pouvoirs élastiques, poussant ces derniers à lui crier après et parfois le frapper. Il faudrait aussi noter qu'il devient plus glouton à travers la série puisqu'il existe des moments où il devient monstrueusement obèse, quoiqu'il perde du poids par l'intermédiaire de son fruit de démon qu'il lui permet d'être très flexible au niveau de son poids. Aussi, après les événements d'Enies Lobby, Luffy semble avoir développé la narcolepsie, tout comme son "frère" Ace et son grand-père Garp, quoique ce fut pour une courte période (il est tout de même capable de manger en dormant).</p>
                    <p>À l'instar de Sabo, son père Monkey D. Dragon, de son frère Ace, de Gold Roger et peut-être même d'autres porteurs du D., Luffy apprécie beaucoup la liberté. Cela le mène à se lancer dans l'aventure et la piraterie (il pense en effet que être le roi des pirates signifie être l'homme le plus libre du monde)</p>
                     <figure>
                        <img src="/image/luffy/luffy_p/Luffy_admiration.png" alt="Luffy emmerveillé" class="imgLeg">
                        <figcaption class="descImg"> Luffy emmerveillé </figcaption>
                    </figure> 
                    <p>Un autre gag en série est son habitude d'être émerveillé par les aptitudes variées de ses ennemis en criant "INCROYABLE" avec des étoiles dans les yeux et autour de la tête. Luffy croit qu'il est "plus cool" quand il porte des armures complètes, mais chaque amure qu'il trouve et porte lui-même finit détruite, soit dans une bataille, soit par quelque autre scénario humoristique. Il s'émerveille également de toute chose bizarre ou rare qu'il rencontre que ce soit une nouvelle arme du Sunny, l'apparition de Brook, alors que tous les autres membres de l'Équipage sont morts de peur. Il insulte aussi constamment ses adversaires en leur donnant des surnoms dégradants (traitant Gecko Moria de "poireau géant" et Ener de "lobe d'oreilles"). Luffy n'a apparemment aucune compétence pour insulter les gens, prenant généralement soit un aspect physique ou une aptitude unique et tentant de le rendre dégradant (comme insulter Zoro de "Quatre-Épées" quand tout le monde se lamentait de l'absence de Vivi).</p>              
                    <p>Luffy n'a également aucun talent pour mentir sur quoi que ce soit. En fait, le plus souvent, Luffy laisse échapper, sans même y penser, ce qu'il sait chaque fois que les gens lui posent des questions concernant des événements qui se sont produits. Il peut cependant aussi garder très longtemps un secret (quand on ne lui pose pas la question), ainsi aucun de ses amis ne savait qu'Ace n'était pas son vrai frère mais le fils de Roger jusqu'à ce que l'information devienne publique, et son propre passé comporte de nombreuses zones d'ombre (comment se fait-il qu'il ait grandi avec pour seule famille son grand-père Garp ? Qui est sa mère ?).</p>
                    <figure>
                    <img src="/image/luffy/luffy_p/3258739634_1_3_5iX2xSho.jpg" alt="Luffy aka le gars qui sait pas mytho" class="imgLeg">
                        <figcaption class="descImg"> Luffy ou le gars qui sait pas mytho </figcaption>
                    </figure>       
                    <p>Par ailleurs, Luffy a tendance à avaler ses lèvres et à tourner sa tête d'un côté lorsqu'une attaque ou technique ne semble pas fonctionner sur lui, tel que les attaques électriques d'Ener ou le Mero Mero no Mi de Boa Hancock.</p>            
                    <p>Luffy ne tue jamais aucun de ses ennemis (peu importe à quel point ils ont le cœur froid), au lieu de cela, il les envoie fréquemment dans les airs, les assomme ou les bat jusqu'à ce qu'ils soient proches de la mort et perdent connaissance. Oda explique que c'est une question de moralité en tant que "comment punir les gens mauvais de leurs crimes" – il sent que tuer les méchants serait un peu trop léger, puisqu'il considère que leur laisser la vie sauve pour voir leur rêves ruinés serait une punition plus appropriée. Ironiquement, certaines des personnes qu'il a battues deviennent pacifiques ou même ses alliés après leurs défaites, par exemple, Wapol qui devient un riche dirigeant d'une fabrique de jouets, mais il est peut-être devenu mauvais une nouvelle fois après avoir créé son nouveau royaume. Le cas de Mr 2 Bon Clay est également parlant : il est d'abord son ennemi en tant que membre de Baroque Works, mais ils lient ensuite une amitié éternelle qui fera d'eux des alliés fidèles à Impel Down. Cependant, cela peut avoir changer après l'ellipse puisqu'il a été impliqué dans un complot visant à assassiner Big Mom.</p>
                    <p>Une autre caractéristique dominante de Luffy est sa nature humble : il ne se vante pas de ses victoires contre des adversaires puissants, quoiqu'il lui arrive de dire que personne ne l'a vaincu, ce qui n'est pas vrai, ayant été battu plusieurs fois par Ace et Sabo en tant qu'enfant, deux fois par Smoker (quoique ça n'a pas été fatal), deux fois par Crocodile avant de l'avoir vaincu, une fois par Aokiji, une fois par Rob Lucci, une fois par Kuma et une fois par Magellan. Il reste modeste malgré qu'il ait fait des choses exceptionnelles comme battre des pirates du niveau d'un Capitaine Corsaire ou du niveau d'un commandant d'Empereur et ordonner de brûler le drapeau du Gouvernement Mondial à Enies Lobby. Quand Franky souligne ce dernier fait, Luffy répond seulement que ce n'est rien, puisque lui et son équipage sont venus uniquement ici pour reprendre un membre d'équipage qu'on leur a pris (Robin). Lorsque Sengoku tente de trouver une façon de couvrir la défaite de Gecko Moria en ordonnant à Bartholomew Kuma de tuer l'Équipage du Chapeau de Paille, le grand-père de Luffy, le vice-amiral Monkey D. Garp, lui dit, " Ah, ne t'inquiète pas, Sengoku ! Luffy n'est pas du genre à se vanter de sa victoire sur Gecko Moria de toute façon ! "</p>
                    <p>Malgré sa passion pour le combat, Luffy refuse généralement de combattre une personne qu'il ne considère pas personnellement comme étant un ennemi, préférant, soit lui parler, soit éviter la confrontation. Au cours de la série, Luffy est devenu plus mature et réfléchi, bien qu'il ne montre cette partie de sa personnalité que lorsque lui et ses amis sont dans une situation catastrophique ou que quelqu'un l'insulte, traitant des gens comme lui et et leurs convictions de stupides ; en dehors de cela, il est toujours la même personne qu'il était au début de la série.</p>
                    <p>Il ne s’irrite presque jamais contre des gens normaux, mais il existe quelques exceptions, comme quand ils semblent avoir un goût opposé concernant la nourriture ou quand ils demandent s’ils peuvent jeter un coup d’œil à ses "bijoux de famille".</p>
                    <figure>
                    <img src="/image/luffy/luffy_p/381270285.gif" alt="Luffy et barbe noire" class="imgLeg">
                        <figcaption class="descImg"> Luffy et barbe noire </figcaption>
                    </figure>                    
                    <p>Luffy n’a également aucun problème avec d’autres gens qui étirent et jouent avec son corps élastique. Cependant, il peut devenir un peu irrité s’ils le font alors qu'il est en plein milieu d’un repas. Luffy appelle chaque créature d'apparence mixte qu'il trouve par sa partie secondaire (non dominante). Sur l'Île de Gaimon, le chien/poulet était appelé un poulet alors qu'il était surtout un chien, le serpent/lapin un lapin, quoique c'était surtout un serpent, et le cochon/lion un lion, quoique c'était surtout un cochon. Ceci devint un gag en série : plus tard, lorsqu'il rencontra des Banana-Crocos, il les appela des bananes avec des crocodiles qui leur sont attachées (de toute façon, d'après lui, ça n'a pas d'importance qu'il s'agisse de crocodiles ou de bananes car les deux se mangent, on voit d'ailleurs dans son flash-back, bien plus tard dans la série, qu'il mangeait réellement des crocodiles lorsqu'il était enfant). Aussi, après avoir vu Pierre se transformer, il continua à faire référence à lui comme étant un "cheval" au lieu d'un oiseau. En relation à ce gag en série, sur l'île de Long Ring Long Land, il a appelé tous les animaux en fonction de ce à quoi il pensait qu'ils ressemblaient plutôt que les espèces réelles qu'ils étaient.</p>
                    <p>L'intérêt de Luffy pour les femmes est un sujet complexe : dans un SBS, Oda a déclaré que la raison pour laquelle Luffy a semblé excité lorsqu'il a vu Nami nue à Alabasta, mais est resté neutre lorsqu'il a vu Hancock dans la même situation, c'est parce qu'il était avec Usopp au moment où il a vu Nami, et puisque Usopp est quelqu'un de son âge, il a une mauvaise influence sur son comportement. Il semble également avoir peu ou aucun intérêt romantique, ayant refusé nonchalamment les propositions de mariage faites à lui par Laura et Hancock sans arrière-pensée.</p>
                    <p>Luffy est très fidèle envers ses membres d'équipages et ses autres amis, et peut rapidement perdre son sang-froid si le moindre mal leur est fait par n'importe quel moyen (un trait qu’il partage apparemment avec le défunt Seigneur des Pirates). Luffy est même prêt à faire des choses drastiques pour venger et défendre ceux qui lui sont chers, même si cela implique de briser une promesse faite à ses amis, tel que mettre Bellamy K.O. pour avoir attaqué l'équipage de Montblanc Cricket, même s'il a promis à Nami qu'il ne chercherait pas la bagarre, et donner un coup de poing au visage du Noble Mondial Saint Charlos pour avoir tiré sur Octo,malgré la promesse de ne pas défier les Nobles Mondiaux. De plus, Luffy croit également que toutes les personnes devraient être fidèles à leurs amis, et si Luffy voit quiconque trahir ses camarades, il a le réflexe de défendre leurs victimes (même si ce sont des ennemis).Les exemples notables sont le capitaine Kuro qui massacre son propre équipage, Don Krieg qui attaque Gyn et Boa Hancock qui pétrifie les propres membres de sa tribu Kuja. En outre, selon son propre aveu dans l'arc G-8, il est sentimental.</p>
                    <p>Luffy a acquis une réputation de pirate extrêmement imprudent et, dans certains cas, fou. Toutefois, contrairement à d’autres pirates qui ont acquis une réputation pour être psychotiques (tel que Caribou, l’assassin de Marines et Bellamy) ou par des actes inutiles et violents contre des civils (Eustass Kidd) ou l’autorité, la réputation de Luffy lui vient de ses actions ayant pour but de sauver ses amis et l'opposant à des ennemis puissants ou, à plusieurs reprises, au Gouvernement Mondial (à Enies Lobby, Impel Down, Marineford,et lors de l'incident avec les Dragons Célestes). Il a tendance à aller beaucoup plus loin que les autres pirates car il ne se préoccupe pas de respecter les règles du Gouvernement Mondial ou des pirates, et est toujours optimiste.</p>
                    <figure>
                    <img src="/image/luffy/luffy_p/One_Piece_Luffy_Chopper_Amazed_and_Amazing.jpg" alt="Luffy et Chopper impréssionner par Sogeking" class="imgLeg">
                        <figcaption class="descImg"> Luffy et Chopper impréssionner par Sogeking </figcaption>
                    </figure>                   
                    <p>Luffy admire les héros (qu'il reconnaît à leur cape, comme il le dit à Chopper lorsqu'il voit Sniperking), quoiqu'il déclare avec véhémence qu’il ne veut pas vraiment en être un, son raisonnement traduisant plus ou moins que la définition d’un bon héros est d’être entièrement désintéressé, à l'inverse d'un pirate. Ironiquement, beaucoup des actions de Luffy sont essentiellement altruistes, son égoïsme tournant essentiellement autour de sa gourmandise et de sa soif d’aventure. Les gens qu'il rencontre sont donc nombreux à penser qu’il est une sorte de héros (à Alabasta, sur l'île des Hommes-poissons ou encore à Thriller Bark), mais il ne se voit pas comme tel d'après ses propres conceptions. Toutefois, il est convaincu par Jinbe dans le cadre de son plan de devenir le héros de l’Île des Hommes-Poissons avec un accord de viande.</p>
                    <p>L'altruisme apparent de Luffy inspire souvent les autres à se mettre de son côté. C'est ainsi le cas de Boa Hancock (qui le voit comme une exception parmi les hommes, qu'elle méprise tous exceptés Fisher Tiger et Rayleigh, tous deux l'ayant sauvée par le passé) et Emporio Ivankov, qui ne lui serait pas venu en aide dans le cas contraire (même si le choix d'Ivankov de l'aider est aussi grandement motivé par le fait que Luffy est le fils de son ami Dragon). Luffy montre également du respect pour les choses pour lesquelles une personne est prête à mourir, qu'il s'agisse d'un trésor ou d'un secret, au point même de combattre pour protéger ce qu'une personne considère comme précieux. L'action la plus notable à ce sujet est sa protection du secret des Soeurs Gorgones en utilisant son propre corps pour couvrir la marque sur le dos de Sandersonia, même si elles essayaient de le tuer.</p>
                    <p>Toutefois, malgré toutes ses caractéristiques particulières (dont son comportement idiot), la partie la plus essentielle de la personnalité de Luffy est sa capacité véritable à se faire des alliés d'absolument n'importe qui, (incluant des anciens ennemis, des "méchants" actuels et même Barbe Blanche), dont Mihawk dit que ceci est la capacité la plus exceptionnelle au monde.</p>
                    <p>Également, en tant que petit gag en série, Luffy dit à ses membres d'équipage d'économiser leur argent, uniquement pour pouvoir leur annoncer que le but est de le nourrir. Un autre gag en série est le fait que Luffy dise de façon désinvolte et en présence d'inconnus un secret comme l'identité du père d'Ace et de son propre père, avant d'ajouter que c'est un secret qu'il n'est pas censé révéler. Il partage ceci avec son grand-père.</p>
                    <p>Toujours dans les gags en série, à chaque fois qu’un Escargophone sonne et que personne ne veut répondre à l'appel ou qu’on avertit tout le monde du danger d'y répondre, Luffy y répond et se présente formellement, déclarant qu’il deviendra le Seigneur des Pirates, ignorant complètement les dangers que l’appel pourrait avoir.</p>
                    <p>Lorsque son frère de cœur Ace est tué à Marineford, l'épreuve psychologique que constitue la mort d'Ace dans ses bras le fait tomber dans un état catatonique. Après s'être réveillé de son état comateux, Luffy sombre dans une rage furieuse et cause des ravages dans la forêt d'Amazon Lily pour calmer son chagrin, sa frustration et sa colère.</p>
                    <figure>
                        <img src="/image/luffy/luffy_p/Ace_and_luffy003.png" alt="Aie Ace est vraiment pas en forme" class="imgLeg">
                            <figcaption class="descImg"> Aie Ace est vraiment pas en forme</figcaption>
                    </figure> 
                    <p>Par la suite, Luffy a été contraint de se réévaluer lui-même et est arrivé à la conclusion qu'il avait été trop naïf et qu'il était faible et indigne de devenir le Seigneur des Pirates, tombant dans un état de dépression et d'apitoiement sur lui-même. Certains encouragements de Jinbe et de Rayleigh ont donné à Luffy un courage renouvelé pour continuer de poursuivre son rêve. Après l'ellipse, il dit à Rayleigh qu'il sera le Seigneur des Pirates, ayant retrouvé sa confiance à se battre pour son rêve.</p>
                    <p>Avant l’ellipse, Luffy a affiché un côté de lui-même où il se retrouvait mêlé dans des bagarres pour des enjeux inutiles (par exemple, il s’est presque retrouvé dans une bagarre avec Barbe Noire à Mock Town sur une question concernant la qualité des tartes que la taverne leur a servies). Cette tendance semble avoir diminué après les deux ans d’entraînements, il préfère maintenant mettre fin aux conflits avec le moins d’efforts possible, comme on le voit quand il met K.O. l’Équipage du Faux Luffy en utilisant le Fluide sans se troubler ou dire un mot. Cependant, il est probable qu’il ait fait ceci tout simplement pour éviter toute interférence avec son équipage qui met les voiles, en gardant profil bas, comme promis à Hancock. Il est facilement convaincu par Jinbe de suivre son plan, s'embrouillant lui-même entre son propre exemple (il ne veut pas être un héros parce qu'un héros partage la viande, alors que lui, pirate, garde tout pour lui) et la réalité (Jinbe lui assure qu'il pourra manger toute la viande, bien qu'on ignore de quelle viande il s'agit puisque celle-ci n'existe que dans l'exemple donné par Luffy). Il accepte donc d'être un héros, montrant une fois de plus son manque de logique et son amour pour la viande.</p>        
            </section>
            <section>
                <h1 id="Gal"><a href="#Summary">Galerie</a></h1>
                    <ul>
                        <li><img src="/image/luffy/Luffy-gal/Luffy-PreElipse.png" alt="Luffy Pré Elipse"></li>
                        <li><img src="/image/luffy/Luffy-gal/Luffy-PostElipse.png" alt="Luffy Post Elipse"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Luffy_enfant.png" alt="Luffy enfant"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Nightmare_Luffy.png" alt="Nightmare Luffy"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Luffy_Marineford.png" alt="Luffy a MarineFord"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Luffy-PunkHazard.png" alt="Luffy a Punk Hazard"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Luffy-Dressrosa.png" alt="Luffy a Dressrosa"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Lucy.png" alt="Luffy déguiser en Lucy"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Luffy-WholeCake.png" alt="Luffy a Whole Cake"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Luffy-Classe.png" alt="Luffy qui a la Classe"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Luffy-Avis.png" alt="Avis de Recherche de Luffy"></li>
                        <li><img src="/image/Luffy/Luffy-gal/Luffy-Avis2.png" alt="Avis de Recherche de Luffy 2"></li>
                    </ul>
            </section>
        </main>
        <footer id="mainFooter">
            <p>Copyright François BESNARD</p>
        </footer>
    </body>
</html>