<!DOCTYPE html>
<html lang="fr">
    <head>
        <title>Le spécialiste de l'info sur ONE PIECE</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="/css/visu.css"/>
    </head>
    <body>
        <header>
            <!--Menu qui s'ouvre afin de pouvoir sélectionner l'un des différent equipage que l'on souhaite voir-->
            <?php include('../menu.php');?>
        </header>
        <main>
            <!--Début de la page du personnage-->
            <section class="descP">
                <h1> Nami </h1>
                <figure>
                    <img src="/image/Nami/Nami_p/Nami_Anime_Post_Ellipse_Infobox.png" alt="Nami" class="mainImg">
                </figure>
                <p>Nami, alias "La Chatte Voleuse" (泥棒猫, Dorobō Neko), est la navigatrice de L'Équipage du Chapeau de Paille. Elle est la deuxième personne à se joindre à l'équipage après Zoro. Elle a brièvement "trahi" l'Équipage du Chapeau de Paille pendant l'Arc Baratie et les rejoignit officiellement à la fin de l'Arc d'Arlong après que son passé et ses intentions furent révélés. Son rêve est de dessiner une carte complète du monde. Sa prime actuelle s'élève à 66 000 000.</p>
            </section>
            <!--Fin de la présentation classique et début du sommaire des carac du perso-->
            <aside>
                <h1 id="Summary"> Sommaire</h1> 
                <ol>    
                    <li><a href="#App"> Apparence</a> 
                        <ol>
                            <li><a href="#AG"> Apparence Générale</a></li>
                            <li><a href="#APoE"> Apparence Pré Elipse</a></li>
                            <li><a href="#APrE"> Apparence Post Elipse</a></li>
                        </ol>
                    </li>
                    <li><a href="#Pers"> Personnalité</a> </li>
                    <li><a href="#Gal"> Galerie</a> </li>
                </ol>
            </aside>
            <section class="descP">
                <h1 id="App">Apparence</h1>
                    <h2 id="AG"> <a href="#Summary">Apparence Générale</a></h2>
                    <p>Nami est une jeune fille de taille moyenne et mince, avec des cheveux oranges et les yeux bruns clairs. Beaucoup de gens dans la série, la considèrent comme étant une femme très attirante. Elle a un tatouage noir (bleu dans l'animé) sur son épaule gauche. Ce tatouage, qui représente une mandarine et un moulinet (un hommage à Belmer, Nojiko et Genzo, qu'elle considère comme ses parents), remplace le tatouage de l’équipage d'Arlong qu'elle portait avant les événements de l'Arc Arlong. Elle porte aussi un bracelet en or sur son poignet gauche donné par Nojiko.</p>
                    <p>Son physique global a beaucoup mûri au fil de la série (si ce n'est qu'à cause de l'évolution du style graphique de la série). Ses vêtements changent fréquemment tout comme Robin et Vivi, de même que sa coupe de cheveux. Beaucoup de ses chemises comportent des mots de quatre lettres, comme "MODE", ou "GOLD" ou encore "EVIL", tout comme Belmer qui portait une chemise avec le mot "MACE". Sur son poignet gauche, elle porte le Log Pose dont elle a besoin pour exercer sa fonction de navigatrice. Après l’arc Arlong, Nami change de tenue à chaque arc, habituellement pour des paires de chaussures à talons hauts et des jupes avec deux anneaux sur les côtés. Ses chaussures favorites sont des spartiates marron à talons hauts, qui ne semblent pas affecter la façon dont elle marche ou sa vitesse. Bien qu'elle ait tendance à se coiffer les cheveux soigneusement, il est tout de même possible que, quelques fois, une mèche de cheveux se dresse sur sa tête.</p>
                    <p>Elle porte une sangle attachée autour de la cuisse dans laquelle elle garde chaque partie de son Clima-Tact.</p>
                    <h2 id="APoE"> <a href="#Summary">Apparence Pré Elipse</a></h2>
                    <p>Nami avait les cheveux courts, souvent détachées ou parfois attachées en couette ou en queue-de-cheval. Ses trois mesures sont (selon Sanji et le créateur de la série, Eiichiro Oda) B95-W55-H85, ce qui fait de sa poitrine une taille I au Japon. Elle est la plus petite de l'équipage (1,9 m), Chopper excepté.</p>
                    <p>Avant l'Arc du Village de Sirop, Nami portait une mini-jupe orange qui avait comme motifs deux cercles emplis de marron orangé en leur centre et une chemise à manches assez courtes pour cacher le tatouage de la jeune femme. Ses chaussures à talons étaient de couleur marron.</p>
                    <p>Durant l'Arc Baratie, elle s'accoutrait d'une chemise rose, les lettres "W" et "B" inscrites dans un cercle blanc centré dans celle-ci. Ses manches arboraient deux lignes blanches à leur extrémité. Elle portait également sa mini-jupe et ses chaussures habituelles.</p>
                    <p>Durant l'Arc Arlong, Nami arborait une camisole vert clair avec des motifs de fleurs vert foncé, un pantalon noir avec deux anneaux jaunes sur le côté ainsi qu'une paire de chaussures à talons. Elle mit brièvement un gant afin de cacher sa cicatrice lorsqu'elle avait poignardé sa main pour faire croire qu'elle avait assassiné Usopp. Après l'arc, elle portait une simple chemise blanche ainsi qu'une mini-jupe bleue qui arborait deux anneaux blancs sur le côté. Pour la première fois, elle portait des vêtements sans manches, exposant ainsi son tatouage des Pirates d'Arlong. Plus tard, dans un accès de rage incontrôlable, elle poignarda sans relâche son tatouage dans l'espoir de le détruire. Cependant, elle fut arrêtée de force par Luffy. La jeune femme a finalement demandé au Dr. Nakoh de le lui enlever. Le médecin ne pouvait malheureusement pas effacer totalement le tatouage à cause de la nature indélébile de celui-ci et des coups de couteau qu'elle s'est infligée, laissant une cicatrice. Elle a alors recouvert celle-ci par un autre tatouage qui représentait le croisement entre une mandarine et un moulin à vent, en hommage à Belmer et Genzo.</p>
                    <p>Durant l'Arc Loguetown, elle était vêtue d'un t-shirt bleu marine, d'une mini-jupe bleu foncé avec deux anneaux blancs sur le côté et d'une paire de sandales bleu marine à hauts-talons.</p>
                    <p>De l'Arc Île du Navire de Guerre à l'Arc Laboon, Nami portait une chemise bleue sans manches striée de petites lignes blanches avec un cœur bleu en plein centre, une mini-jupe bleue et ses habituelles chaussures à talons.</p>
                    <p>Durant l'Arc Whiskey Peak, elle était vêtue d'un maillot noir avec le mot "MODE" inscrit en rose. Elle portait sa jupe et ses chaussures habituelles.</p>
                    <p>Durant l'Arc Little Garden, la jeune femme portait une chemise blanche à manches bleues, sa mini-jupe jaune ainsi que ses chaussures à talons. Après avoir échappé au "Giant Candle Service Set" de Mr. 3, sa chemise à été brûlée, révélant une paire de soutiens-gorge noire.</p>
                    <p>Durant l'Arc Royaume de Drum, elle a porté plusieurs tenues. Au début, Nami portait un pull-over à manches courtes en coton bleu pâle, sa chemise jaune et des sandales à talons hauts. Pendant que Luffy et Sanji la transportaient afin qu’elle soit soignée par le Dr. Kureha (elle avait attrapé une fièvre durant l’arc précédent), Nami portait une parka à carreaux avec une capuche, dont les couleurs étaient blanc, orange et jaune vif (dont Luffy se revêtit plus tard). Alors qu’elle récupérait chez le Dr. Kureha, elle portait un pyjama bleu clair et une couverture violet clair avec des fines lignes de fourrures brune lorsqu’elle s’aventura hors de sa chambre. À la fin, Nami portait un long manteau marron avec une capuche, un col et un ourlet ainsi que des bottes d’hiver marron à talon haut.</p>
                    <p>Durant l’Arc Alabasta, elle portait un ensemble blanc composé d’une tunique et d’un foulard couvrant la tête afin de protéger sa peau dans le désert. Elle a retiré ces habits lors de son combat contre Paula et révélé une tenue de danseuse (que Sanji avait acheté plus tôt durant l’arc) après que Paula les ait endommagés. La tenue de danseuse était composée d’un top bleu et violet avec un voile rose à une longue jupe blanche dont la partie haute était bleue. Plus tard Nami a déchiré cette jupe du bas vers le haut afin de faciliter la course à pied. Finalement, elle se vêtit d’une chemise blanche à manches longues et d’une jupe marron afin que ses vêtements coordonnent avec ses chaussures à talons habituelles.</p>
                    <p>Durant l’Arc Jaya, elle portait une chemise blanche striée de lignes bleues, sa jupe habituelle et ses chaussures à talons.</p>
                    <p>Durant la première partie de l’Arc Skypiea, alors qu’elle explorait Angel Beach et Upper Yard, elle portait un bikini décoré d'un motif de nuages colorés en bleu, bleu clair et blanc. Elle avait assorti son top avec un pantalon/short marron et était pieds-nus. Après son retour d’Upper Yard, elle enfila une chemise jaune clair à manches courtes sur son bikini et mit des sandales à talon oranges. Sanji manifesta sa réprobation alors que Nami enfilait la chemise… Elle porta également des lunettes pendant une courte période et ramena ses cheveux en arrière avec des couettes afin de dégager ses yeux, elle conserva les cheveux attachés jusqu’à son retour sur Upper Yard. Nami retira finalement sa chemise lorsqu’elle dut plonger dans l’eau et resta en bikini ; Sanji fut ravi de voir cela. Finalement, elle se changea et opta pour un caraco gris à zip, portant l’inscription « EVIL » imprimée en caractères bleus, un jean bleu découpé et une paire de sandales grises.</p>
                    <p>Durant l’Arc Davy Back Fight, Nami s'était accoutrée d'un débardeur noir révélant son nombril avec le mot "GOLD" écrit dessus en jaune, d'un jean blanc avec un anneau blanc sur chaque côté de celui-ci et d'un bracelet. Elle avait également ses chaussures à talons habituelles.</p>
                    <p>Durant l’Arc Water Seven, elle portait une chemise bleue marine avec une cravate bleu clair avec des petits points bleus à son extrémité. Elle compléta sa tenue avec une jupe blanche plissée qui a une paire d'anneaux dorés à chaque côté. Après le combat opposant Luffy face à Usopp, elle troqua ses vêtements contre une camisole violette avec le chiffre "3" imprimé dessus en blanc, une mini-jupe blanche plissée et ses habituelles chaussures à talons.</p>
                    <p>Durant l’Arc Enies Lobby, elle était initialement vêtue d'un haut de bikini marron au centre et jaune sur le contour, d'une jupe bleue plissée et d'une paire de spartiates noires. Initialement, elle portait aussi une veste en jean bleu, mais lorsque la jeune navigatrice fut cernée par Kumadori, elle fut obligée de s'en débarrasser pour s'enfuir.</p>
                    <p>Durant l'Arc Post-Enies Lobby, Nami portait une mini-robe jaune à capuche avec les lettres "GC" inscrites en orange ainsi que ses sandales habituelles.</p>
                    <p>Durant l’Arc Thriller Bark, elle arborait plusieurs tenues. L'une d'elles était un chandail rose à manches longues et à col blanc. Plus tard, après avoir été kidnappée par Absalom, ce dernier lui a enfilé une robe de mariée blanche et des hauts-talons de même couleur. Il lui a également coiffé ses cheveux en queue-de-cheval. Pendant un court moment, elle a troqué ses sandales contre des bottes à hauts-talons, mais les a finalement reprises vers la fin de l'arc.</p>
                    <p>Durant l’Arc Sabaody, la tenue de Nami se composait d'un t-shirt orange avec des motifs floraux de couleurs orange ou violet, d'un short blanc et de ses habituelles sandales à hauts-talons. Noter qu'elle portait un collier à perles jaunes autour de son cou.</p>
                    <p>Lors de la séparation de l'équipage au Chapeau de Paille, elle s'accoutrait d'une chemise rose, d'un short bleu et de ses sandales.</p>
                    <h2 id="APrE"> <a href="#Summary">Apparence Post Elipse</a></h2>
                    <p>Les cheveux de Nami sont plus longs et descendent jusqu'au bas de son dos. Tout comme Robin, sa poitrine a considérablement pris du volume et les courbes de son corps sont plus prononcées. Elle a également légèrement grandi (1,70 m). D'ailleurs, jusqu'à maintenant, ses tenues sont principalement constituées de hauts de bikinis révélateurs et de jeans taille basse, il n'y a que la couleur et les motifs qui changent. Ses nouvelles mesures sont B98-W58-H88.</p>
                    <p>Durant l'Arc Retour à Sabaody et une grande partie de l'Arc Île des Hommes-Poissons, sa tenue se composait d'un haut de bikini révélateur, d’un jean bleu, une paire de sandales orange à talons hauts et une paire de boucles d'oreilles en forme de perles. Depuis son arrivée dans le Nouveau Monde, Nami arbore une nouvelle ceinture avec le signe Symbole Berry.gif en plein milieu. Elle garde également dedans les morceaux de son Perfect Clima-Tact.</p>
                    <p>Avant de quitter l'Île des Hommes-Poissons, elle troqua son haut de bikini contre un autre de couleur rouge et de la marque Criminal. Le Ministre de la Gauche lui donnera un nouveau Log Pose, mieux adapté à la navigation dans les eaux tumultueuses du Nouveau Monde. Après que l'équipage ait quitté l'île, Nami décida de se détendre en prenant un bain et se déshabilla. Cependant, elle fut très vite interrompue à cause de l'arrivée d'un White Storm. La navigatrice se précipita alors sur le pont, vêtue d'un simple peignoir à capuche bleu. À ce moment, elle avait sur elle son nouveau Log Pose, son bracelet en or et ses boucles d'oreilles en perles ainsi qu'une paire de sandales brune. Cependant, Nami a démontré ne les avoir portés que très brièvement dans l'animé, car elle les perdit lorsque le White Storm emporta leur navire.</p>
                    <p>Durant l’Arc Punk Hazard, Nami met un nouveau soutien-gorge rouge et jaune de la marque Criminal avec le même jean et des talons-hauts. Plus tard, dans les terres glacées, Nami a de nouveaux vêtements créés par Kinemon (grâce à son mystérieux Fruit du Démon), un manteau noir et des gants roses. Mais sachant que c’était à ce moment là que Sanji était dans le corps de Nami, lorsque ce dernier est parti récupérer le corps du samouraï, il a dû retirer les vêtements pour plonger dans le lac et les vêtements ont donc disparu à ce moment la. Lorsque Sanji est ressorti du lac avec le corps du samouraï, ce dernier lui a fait apparaître les mêmes vêtements, mais de couleurs différentes. Après que Nami et Sanji ont récupéré leurs corps respectifs grâce à Law, Nami a remarqué la différence de couleur dans les vêtements et a pensé que Sanji s'est dénudé. Nami a ensuite retiré les vêtements (créé par Kinemon) lorsque tout le monde, elle y compris, sont rentrés dans le labo de César (car il ne faisait plus froid).</p>
                    <p>Après être retournée au Thousand Sunny, elle s'est changée et porte des vêtements d'hiver réels et plus personnalisés et a remplacé ses vêtements qui n'étaient pas adaptés au froid, mettant un manteau noir avec un col haut avec trois ensembles de boutons d'or maintenus ensemble par des sangles, des gants bruns, un ensemble de leggings noirs au lieu de jeans, et à la place de ses sandales, une paire de bottes marron foncé avec de la fourrure blanche allant jusqu'aux mollets. Une fois l'équipage sorti de Punk Hazard dans des conditions plus agréables, elle portait une chemise rose sans manches avec le mot "HEAT" dessus en lettres rouges avec une photo de bonbons en dessous, un short à rayures bleu et blanc, et ses sandales à talons hauts.</p>
                    <p>Durant l’Arc Dressrosa, la première tenue de Nami se composait d'un débardeur et d'un short. Un peu, plus tard, elle portait un haut de bikini, un short court et des chaussures à très hauts-talons.</p>
                    <p>Durant l'Arc Zou, Nami porte une robe pourpre couverte de perles, qui est un trésor national de Zou. Elle porte toujours ses sandales à talons hauts et ses cheveux sont lâches. En quittant Zo, elle porte une jupe et une chemise avec le numéro "73" dessus et plus tard un manteau de fourrure à capuchon quand l'équipage voyage par temps froid. Avant d'aller à Whole Cake Island, elle porte une jupe bleue avec deux anneaux jaunes sur les côtés et un débardeur blanc.</p>
                    <p>Durant l'Arc Whole Cake, Nami porte un chemisier blanc sans manche, et une jupe rouge à bretelles allant jusqu'au haut de ses cuisses. Lorsque sa tenue brûle, elle prend une salopette bleue très large au niveau des jambes à un des gardes inconscient. Après son arrivée chez les pirates du Firetank, elle se change pour une robe rouge cintrée. Durant la fuite vers l'Île Cacao, elle opte pour une robe à manche longue en laine avec une ceinture ayant le symbole du Berry.</p>
            </section>
            <section class="descP">
                <h1 id="Pers"> <a href="#Summary">Personnalité</a></h1>
                    <p>Nami est l'un des membres les plus intelligents de l'équipage (avec Robin) et la troisième personne la plus intelligente d’East Blue, selon Oda.</p>
                    <p>Au début de la série, Nami méprisait tous les pirates et les considérait comme des mauvaises personnes à cause de ce qu'Arlong et son équipage ont fait à son village. Mais après sa rencontre avec Luffy, son point de vue changea sur les pirates.</p>
                    <p>Elle était prête à donner Luffy à Baggy mais le délivra ensuite, ne pouvant s’abaisser au niveau de vulgaires pirates. Nami est une excellente navigatrice qui peut prévoir instinctivement les changements météorologiques sans instruments, même sur Grand Line, où les caprices imprévisibles du temps et de l'océan rendent ce genre de prévisions impossibles. Hormis le choix de la destination confié à Luffy, c'est elle qui commande et indique les manœuvres à faire à bord du bateau. Ses talents et sa fonction de navigatrice, sont très utiles au cours d'une tempête ou d'un cyclone.</p>
                    <p>Nami éprouve un très profond respect pour son capitaine, mais s'emporte très souvent contre lui, car son attitude stupide et irrationnelle ont souvent raison de sa patience. Nami ferait tout pour de l'argent, notamment accepter le premier défi qui se présente. Son amour de l'argent provient de son enfance où elle a vécu une vie pauvre. Ses coéquipiers lui doivent tous de l'argent sauf Robin. Elle fixe sont taux d’intérêt de 300% et va souvent citer ces dettes pour obliger quelqu'un à faire quelque chose pour elle.</p>
                    <figure>
                        <img src="/image/Nami/Nami_p/Nami_berrys.png" alt="Nami et son Amour de l'argent" class="imgLeg">
                        <figcaption class="descImg"> Nami et son amour de l'argent</figcaption>
                    </figure> 
                    <p>Malgré son amour pour l’argent, ses amis sont bien plus importants pour elle, elle serait prête à tout pour eux comme à les choisir à la place de sa propre vie (avec Ener) ou à donner son argent (sauvetage de Camie). Elle tient à eux bien plus qu'à tous les trésors du monde même si elle préfère le leur cacher. Nami est très autoritaire et donne souvent des ordres, y compris à Luffy alors même qu'il est le capitaine. Tout comme Usopp et Chopper, elle est lâche, peureuse, s'estimant faible et n’aimant pas se battre ; mais quand les personnes qu’elle aime sont en danger, elle n’hésite pas.</p>
                    <p>Elle est consciente des dangers de leur voyage et a une bonne compréhension du monde et des individus (notamment le Capitaine Corsaire Crocodile) que la plupart des membres de son équipage, mais il lui manque la connaissance de certains autres personnages puissants (Amiraux, Hancock, Empereurs…). Après l'ellipse, Nami semble moins violente, comme on peut le voir quand Luffy et Zoro veulent attraper des poissons alors qu’ils sont sous l’eau puisque ce fut Chopper et Usopp qui les réprimanda pour leur comportement irresponsable et non Nami, restée concentrée sur ses manœuvres.</p>
                    <figure>
                        <img src="/image/Nami/Nami_p/Nami_grimace.jpg" alt="Nami qui fait une grimace" class="imgLeg">
                        <figcaption class="descImg"> Nami qui fait une grimace</figcaption>
                    </figure>
                    <p>Malgré tout, elle est aussi l'un des membres de l'équipage ayant le plus de compassion, elle montre rapidement de la sympathie en entendant des histoires tristes comme elle l'a montré au cours de l'incident avec Octo, de plus elle pleure facilement lors des scènes tristes. Par compassion, elle est même prête à pardonner les personnes qui lui ont fait du mal pendant de nombreuses années. Elle essaie de consoler et détendre ses amis, lors de la discussion visant à savoir si Usopp mérite de réintégrer l'équipage où elle a d'ailleurs insisté pour qu’Usopp revienne.</p>
                    <p>Nami est aussi passionnée de mode, elle ne porte jamais deux fois les mêmes vêtements, ce qui n'était pas visible dans les premiers chapitres. Lorsque Nami va faire les courses, elle va parfois dans des boutiques de luxe pour essayer beaucoup de vêtements, elle finit par en acheter une quantité phénoménale tout en s'arrangeant pour les avoir à petit prix. Elle ne semble pas être pudique puisqu'elle porte souvent des vêtements ouverts et courts et permet aux gens d'admirer ses charmes, on le voit notamment sur son avis de recherche. Elle utilise souvent son physique avantageux pour son propre intérêt et permettra même à ses coéquipiers de voir son corps complètement nu (bains d’Alabasta ) mais elle demandera Symbole Berry.gif100 000 à chaque personne qui veut la voir nue.</p>
                    <p>De tous les personnages de One Piece, Nami est le personnage qui est la plus attirée par l'anatomie masculine, d'après Eichiiro Oda. Après l'ellipse de deux ans, elle réagit de façon moins excessive, mais continue de gronder ou frapper ses amis quand il le faut. En fait, elle semble plus calme qu'avant mais est encore sujette à la panique face à un danger imminent. Elle a également développé une grande endurance à l'alcool supérieure au reste de l'équipage, lors d’événements festifs. Elle semble aussi plus sûre d'elle et de ses capacités au combat, comme on le voit lorsqu'elle bat Baby 5 et Buffalo avec Usopp.</p>
                    
            </section>
            <section>
                <h1 id="Gal"><a href="#Summary">Galerie</a></h1>
                    <ul>
                        <li><img src="/image/Nami/Nami_gal/Tenue_de_Nami_durant_l'Arc_Arlong.png" alt="Nami durant l'arc Arlong"></li>
                        <li><img src="/image/Nami/Nami_gal/Nami_Bébé.jpg" alt="Nami Bébé"></li>
                        <li><img src="/image/Nami/Nami_gal/Nami_Enfant.png" alt="Nami Enfant"></li>
                        <li><img src="/image/Nami/Nami_gal/Bell-mère,_Nami_et_Nojiko.png" alt="Bell-mère, Nami et Nojiko"></li>
                        <li><img src="/image/Nami/Nami_gal/Nami_Troisième_Tenue_Arc_Alabasta.png" alt="Nami à Alabasta"></li>
                        <li><img src="/image/Nami/Nami_gal/Nami_nettoyee_par_le_Awa_Awa_no_Mi.png" alt="Nami à Enies Lobby"></li>
                        <li><img src="/image/Nami/Nami_gal/Nami_Avis_de_Recherche_Post_Enies_Lobby.png" alt="Avis de recherche de Nami après Enies Lobby"></li>
                        <li><img src="/image/Nami/Nami_gal/NamiFishmanIsland.png" alt="Nami à l'ile des Hommes Poissons"></li>
                        <li><img src="/image/Nami/Nami_gal/Sanji_dans_le_corps_de_Nami.png" alt="Sanji dans le corps de Nami"></li>
                        <li><img src="/image/Nami/Nami_gal/Nami_Dressrosa.png" alt="Nami et Momonosuke lors de l'arc Dressrosa"></li>
                        <li><img src="/image/Nami/Nami_gal/Nami_Avis_de_Recherche_Post_Dressrosa.png" alt="Avis de recherche de Nami après Dressrosa"></li>
                        <li><img src="/image/Nami/Nami_gal/Nami_tenue_wholecake.png" alt="Nami lors de l'arc Whole Cake"></li>
                        <li><img src="/image/Nami/Nami_gal/Nami_Quatrième_Tenue_Arc_Wano.png" alt="Nami lors de l'arc Wano Kuni"></li>
                    </ul>
            </section>
        </main>
    </body>
</html>